### ISSUE TITLE
Columns in edit page

### ISSUE THREAD

**Issue by cheh** [CherryFramework/cherry-projects#1]
В методе `edit_projects_columns` полностью перезаписываются колонки.
Проблема будет со сторонними плагинами (например, WPML) когда те добавляют свои колонки. 

https://github.com/CherryFramework/cherry-projects/blob/master/admin/includes/class-projects-admin.php#L71-L92

**Comment by shinTM** [comment]
done https://github.com/CherryFramework/cherry-projects/commit/64f2a5ca05e317186ea5c20806bd4fad5110800d
