### ISSUE TITLE
get_the_terms

### ISSUE THREAD

**Issue by cheh** [CherryFramework/cherry-projects#2]
Использование `get_the_terms` с начало для проверки, а потом для получения значения создает дополнительные запросы в базу.

https://github.com/CherryFramework/cherry-projects/blob/master/admin/includes/class-projects-admin.php#L126-L139

**Comment by shinTM** [comment]
done https://github.com/CherryFramework/cherry-projects/commit/36bf275b8a9467e42512b9d787dfd82bfae2adb2
