### ISSUE TITLE
`cherry-post-meta` module initialization

### ISSUE THREAD

**Issue by cheh** [CherryFramework/cherry-projects#3]
Метод `init` лучше перенести на экшены `load-post.php`, `load-post-new.php` с проверкой `get_current_screen()`.

https://github.com/CherryFramework/cherry-projects/blob/master/admin/includes/class-projects-meta-boxes.php#L35

**Comment by shinTM** [comment]
done https://github.com/CherryFramework/cherry-projects/commit/afb241a9adcc23893da39741c715d777ccda65ee
