### ISSUE TITLE
Plugin options saved for users without the `manage_options` capability

### ISSUE THREAD

**Issue by ghost** [CherryFramework/cherry-projects#7]
The **Settings Page** is visible and options are saved successfully for users without the `manage_options` capability.

It's preferable to disable the **Settings Page** for users without `manage_options` capability.

Following lines should be changed:
https://github.com/CherryFramework/cherry-projects/blob/master/admin/includes/class-projects-options-page.php#L459

https://github.com/CherryFramework/cherry-projects/blob/master/admin/includes/class-projects-options-page.php#L599

**Comment by shinTM** [comment]
done https://github.com/CherryFramework/cherry-projects/commit/93abcc4b6fdae7527f3e1e1d2f2817128a0e6cd2
